### ISSUE TITLE
Create tests distinguishing P3 from BT2020

### ISSUE THREAD

**Issue by rcombs** [codelogic/wide-gamut-tests#1]
Could you add a set of files similar to the current ones, but instead of the "base" space being sRGB, have it be P3, with the larger space being BT2020? It'd be nice to have a sample that clearly shows the difference in how a system handles the two (or whether it supports the expanded space of P3 but not of BT2020).

**Comment by codelogic** [comment]
Hi Rodger! I had some time this weekend, the repository is now updated with R2020-P3, hope it helps!
